[package]
name = "wnace/the-cow-company"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Comm = "sleitnick/comm@0.3.1"
TableUtil = "sleitnick/table-util@1.1.5"